categories = [
    'fruits',
    'animals',
    'countries'
]

fruits = [
    'apple', 
    'apricot',
    'avocado', 
    'banana', 
    'blueberry',
    'blackberry',
    'cherry',
    'cranberry',
    'cucumber',
    'eggplant',
    'grape',
    'kiwi',
    'lemon',
    'lime',
    'mango',
    'orange',
    'papaya',
    'peach',
    'pear',
    'pineapple',
    'pomegranate',
    'raspberry',
    'starfruit',
    'strawberry',
    'tangerine',
    'tomato',
    'watermelon'
]

animals = [
    'alligator',
    'bear',
    'bat',
    'bird',
    'butterfly',
    'chihuahua',
    'dragonfly',
    'dragonfish',
    'electric eel',
    'flamingo',
    'fruit bat',
    'golden retriever',
    'goldfish',
    'honey bee',
    'immortal jellyfish',
    'king penguin',
    'komodo dragon',
    'ladybug',
    'labrador retriever',
    'mongoose',
    'north american black bear',
    'octopus',
    'pufferfish',
    'polar bear',
    'red fox',
    'white rhinoceros'
]

countries = [
    'afghanistan',
    'argentina',
    'australia',
    'bolivia',
    'brazil',
    'canada',
    'chile',
    'china',
    'cuba',
    'dominican republic',
    'ecuador',
    'egypt',
    'el salvador',
    'ethiopia',
    'france',
    'germany',
    'guatemala',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'israel',
    'italy',
    'jamaica',
    'japan',
    'madagascar',
    'mexico',
    'new zealand',
    'north korea',
    'paraguay',
    'peru',
    'philippines',
    'portugal',
    'russia',
    'sao tome and principe',
    'south africa',
    'south korea',
    'turkey',
    'united kingdom',
    'united states of america',
    'uruguay',
    'venezuela',
    'vietnam',
]